server {
    listen 80;
    server_name _;

    location /links-bio/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /links-bio/index.html;
    }

    location = /links-bio {
        return 301 /links-bio/;
    }
}