server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /links-bio {
        return 301 /links-bio/;
    }

    location /links-bio/ {
        rewrite ^/links-bio/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }
}